services:
#  caddy:
#    image: caddy:latest
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - caddy_data:/data
#      - caddy_config:/config
#    command: "caddy reverse-proxy --from http://cf-stg.perchbird.dev --to http://web:80"
  
  web:
    image: ghcr.io/projectchronofoil/chronofoilweb:staging
    ports:
      - "80:80"
      - "443:443"
      - "9184:9184"
    volumes:
      - web_data:/web_data/
    env_file:
      - Staging.env
    depends_on:
      - db

  db:
    image: postgres:17.2-alpine3.21
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file:
      - Staging.env

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    command:
      - '--path.rootfs=/host'
    ports:
      - "9100:9100"
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
  
  pg_exporter:
    image: quay.io/prometheuscommunity/postgres-exporter
    ports:
      - "9187:9187"
    depends_on:
      - db
    env_file:
      - Staging.env

volumes:
  web_data:
  pg_data:
  caddy_data:
  caddy_config:
