services:
  web:
    build:
      context: .
      dockerfile: ./src/Development.Dockerfile
    volumes:
      - ./deploy/persistence/web/:/web_data/
      - .:/app/
      - ~/.nuget/packages:/root/.nuget/packages
      # Don't mount these directories
      # These prevent the obj files from referencing the container's nuget dir
      - /app/src/obj/
      - /app/src/bin/
      - /app/deps/Chronofoil.Common/src/obj/
      - /app/deps/Chronofoil.Common/src/bin/
      - /app/deps/Chronofoil.CaptureFile/src/obj/
      - /app/deps/Chronofoil.CaptureFile/src/bin/
      # This prevents the container's dotnet from using launchSettings.json
      - /app/src/Properties/
    ports:
      - "5000:5000"
    env_file: "dev.env"
    command: ["dotnet", "watch", "--project", "/app/src/Chronofoil.Web.csproj"]
  db:
    image: 'postgres:latest'
    ports:
      - "5432:5432"
    volumes:
      - ./deploy/persistence/db/:/var/lib/postgresql/data
    env_file: "dev.env"