services:
  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    command: "caddy reverse-proxy --from cf.perchbird.dev --to http://web:80"
  
  web:
    image: ghcr.io/projectchronofoil/chronofoilweb:latest
    ports:
      - "9184:9184"
    volumes:
      - /var/lib/cf/data/:/web_data/
    env_file:
      - Production.env
    depends_on:
      - db
      - seq_forwarder

  db:
    image: postgres:17.2-alpine3.21
    volumes:
      - pg_data:/var/lib/postgresql/data/
      - pg_backup:/pg_backup/
    env_file:
      - Production.env
    
  seq_forwarder:
    image: ghcr.io/perchbirdd/seq-forwarder:latest
    stdin_open: true
    tty: true
    env_file:
      - Production.env
  
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    command:
      - '--path.rootfs=/host'
    ports:
      - "9100:9100"
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'

  pg_exporter:
    image: quay.io/prometheuscommunity/postgres-exporter
    command: '--no-collector.stat_bgwriter'
    ports:
      - "9187:9187"
    depends_on:
      - db
    env_file:
      - Production.env

volumes:
  pg_data:
  pg_backup:
  caddy_data:
  caddy_config:
