services:
  web:
    build:
      context: .
      dockerfile: ./src/Development.Dockerfile
    volumes:
      - ./:/app/
      - ./web_data/:/web_data/
      - /app/src/obj/
      - /app/src/bin/
      - /app/deps/Chronofoil.Common/src/obj/
      - /app/deps/Chronofoil.Common/src/bin/
      - /app/deps/Chronofoil.CaptureFile/src/obj/
      - /app/deps/Chronofoil.CaptureFile/src/bin/
    ports:
      - "5103:5103"
    env_file: "Development.env"
    working_dir: /app
    command: dotnet watch run --project src/Chronofoil.Web.csproj
    depends_on:
      - db

  db:
    image: 'postgres:17.2-alpine3.21'
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file: "Development.env"
    
volumes:
  pg_data: