services:
  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    command: "caddy reverse-proxy --from cf.perchbird.dev --to http://web:80"
  
  web:
    image: ghcr.io/projectchronofoil/chronofoilweb:latest
    volumes:
      - /var/lib/cf/data/:/web_data/
    env_file:
      - Production.env
    depends_on:
      - db

  db:
    image: postgres:17.2-alpine3.21
    volumes:
      - pg_data:/var/lib/postgresql/data/
      - pg_backup:/pg_backup/
    env_file:
      - Production.env

volumes:
  pg_data:
  pg_backup:
  caddy_data:
  caddy_config:
