services:
  web:
    image: ghcr.io/projectchronofoil/chronofoilweb:latest
    ports:
      - "9185:9184"
    volumes:
      - /var/lib/cf/data/:/web_data/
    env_file:
      - Production.env
    networks:
      - default
      - proxy_net
    deploy:
      restart_policy:
        condition: any
        delay: 5s
      update_config:
        parallelism: 1
        order: stop-first
        failure_action: rollback
        monitor: 15s

  db:
    image: postgres:17.2-alpine3.21
    volumes:
      - pg_data:/var/lib/postgresql/data/
      - pg_backup:/pg_backup/
    env_file:
      - Production.env
    deploy:
      restart_policy:
        condition: any
        delay: 5s
      update_config:
        parallelism: 1
        order: stop-first
        failure_action: rollback
        monitor: 15s

  seq_forwarder:
    image: ghcr.io/perchbirdd/seq-forwarder:latest
    stdin_open: true
    tty: true
    env_file:
      - Production.env
    deploy:
      restart_policy:
        condition: any
        delay: 5s
      update_config:
        parallelism: 1
        order: stop-first
        failure_action: rollback
        monitor: 15s

  pg_exporter:
    image: quay.io/prometheuscommunity/postgres-exporter
    command: '--no-collector.stat_bgwriter'
    ports:
      - "9188:9187"
    env_file:
      - Production.env
    deploy:
      restart_policy:
        condition: any
        delay: 5s
      update_config:
        parallelism: 1
        order: stop-first
        failure_action: rollback
        monitor: 15s

networks:
  proxy_net:
    external: true

volumes:
  pg_data:
  pg_backup:
