name: test
on:
  push:
    branches: ["*"]

permissions:
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x.x'
      - name: Restore
        run: dotnet restore
      - name: Unit Test
        run: dotnet test --filter Category=UnitTest
      - name: Integration Test
        run: dotnet test --filter Category=IntegrationTest